services:
  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: warehouse
      POSTGRES_HOST_AUTH_METHOD: trust
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
    ports:
      - "${PGPORT:-5432}:5432"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure

volumes:
  pg_data:
    driver: local
