boxspread:
  outputs:
    dev:
      dbname: warehouse
      host: 127.0.0.1
      pass: password
      port: 5432
      schema: public
      threads: 4
      type: postgres
      user: postgres
  target: dev
